/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javaapplication1.admin.dchest;
import static javaapplication1.dbconnect.reslist;

/**
 *
 * @author Iulian
 */

public class membru extends javax.swing.JFrame {

    /**
     * Creates new form 
     * bru
     */
    public static dbconnect dbase = new dbconnect();
    public static dbchestionar dchest = new dbchestionar();
    public int raspunsuricorecte, intrebarecurenta, totalrasp;
    public membru() throws SQLException {
        initComponents();
        //reslist = dchest.viewChestionar(jComboBox1.getSelectedItem().toString())
        List<String> strings = new ArrayList<String>();
        strings=dchest.viewTables();
        for (int i = 0; i < strings.size(); i++)
            jComboBox1.addItem(strings.get(i));
        jLabel3.setText("");
        jLabel4.setText("");
        jLabel5.setText("");
        jLabel6.setText("");
        jLabel7.setText("");
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Alegere chestionar");

        jButton1.setText("Start chestionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jButton2.setText("Alege");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Alege");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Alege");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setText("jLabel7");

        jButton5.setText("Inapoi la Login");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel6)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel7)))
                .addContainerGap(262, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jLabel6))
                .addGap(43, 43, 43)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            reslist = dchest.viewChestionar(jComboBox1.getSelectedItem().toString());
            raspunsuricorecte=0;
            totalrasp=reslist.size()/6;
            int nr_col=6;
            jButton2.setEnabled(true);
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
            intrebarecurenta=1; int j=0;
                        jLabel3.setText(reslist.get(6*j+1));
                        jLabel4.setText(reslist.get(6*j+3));
                        jLabel5.setText(reslist.get(6*j+4));
                        jLabel6.setText(reslist.get(6*j+5));
            //intrebarecurenta++;  
            jLabel7.setText("Raspunsuri corecte: "+raspunsuricorecte+" din "+totalrasp);
        } catch (SQLException ex) {
            Logger.getLogger(membru.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            reslist = dchest.viewChestionar(jComboBox1.getSelectedItem().toString());
            int nr_col=6;
            int j=0;
        
            if(intrebarecurenta<reslist.size()/6){
                        //or (int i = 0; i < nr_col; i++){
                        jLabel3.setText(reslist.get(6*intrebarecurenta+1));
                        jLabel4.setText(reslist.get(6*intrebarecurenta+3));
                        jLabel5.setText(reslist.get(6*intrebarecurenta+4));
                        jLabel6.setText(reslist.get(6*intrebarecurenta+5));
                        Integer rasp = 1;
                        if (rasp==Integer.parseInt(reslist.get(6*(intrebarecurenta-1)+2)))
                        {
                            raspunsuricorecte++;
                            jLabel7.setText("Raspunsuri corecte: "+raspunsuricorecte+" din "+totalrasp);
                        }
            intrebarecurenta++;          
            }
            else {
                //daca e ultima intrebare
                Integer rasp = 1;
                        if (rasp==Integer.parseInt(reslist.get(6*(intrebarecurenta-1)+2)))
                        {
                            raspunsuricorecte++;
                            jLabel7.setText("Raspunsuri corecte: "+raspunsuricorecte+" din "+totalrasp);
                        }
                        jLabel3.setText("");
                        jLabel4.setText("");
                        jLabel5.setText("");
                        jLabel6.setText("");
            }
             
        } catch (SQLException ex) {
            Logger.getLogger(membru.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            reslist = dchest.viewChestionar(jComboBox1.getSelectedItem().toString());
            int nr_col=6;
            int j=0;
        
            if(intrebarecurenta<reslist.size()/6){
                        //or (int i = 0; i < nr_col; i++){
                        jLabel3.setText(reslist.get(6*intrebarecurenta+1));
                        jLabel4.setText(reslist.get(6*intrebarecurenta+3));
                        jLabel5.setText(reslist.get(6*intrebarecurenta+4));
                        jLabel6.setText(reslist.get(6*intrebarecurenta+5));
                        Integer rasp = 2;
                        if (rasp==Integer.parseInt(reslist.get(6*(intrebarecurenta-1)+2)))
                        {
                            raspunsuricorecte++;
                            jLabel7.setText("Raspunsuri corecte: "+raspunsuricorecte+" din "+totalrasp);
                            System.out.println("Raspuns corect!");
                        }
                        else
                        {
                            System.out.println("Raspunsgresit!");
                        }
            intrebarecurenta++;          
            }
            else {
                //daca e ultima intrebare
                Integer rasp = 1;
                        if (rasp==Integer.parseInt(reslist.get(6*(intrebarecurenta-1)+2)))
                        {
                            raspunsuricorecte++;
                            jLabel7.setText("Raspunsuri corecte: "+raspunsuricorecte+" din "+totalrasp);
                        }
                        jLabel3.setText("");
                        jLabel4.setText("");
                        jLabel5.setText("");
                        jLabel6.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(membru.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            reslist = dchest.viewChestionar(jComboBox1.getSelectedItem().toString());
            int nr_col=6;
            int j=0;
        
            if(intrebarecurenta<reslist.size()/6){
                        //or (int i = 0; i < nr_col; i++){
                        jLabel3.setText(reslist.get(6*intrebarecurenta+1));
                        jLabel4.setText(reslist.get(6*intrebarecurenta+3));
                        jLabel5.setText(reslist.get(6*intrebarecurenta+4));
                        jLabel6.setText(reslist.get(6*intrebarecurenta+5));
                        Integer rasp = 3;
                        if (rasp == Integer.parseInt(reslist.get(6*(intrebarecurenta-1)+2)))
                        {
                            raspunsuricorecte++;
                            jLabel7.setText("Raspunsuri corecte: "+raspunsuricorecte+" din "+totalrasp);
                            System.out.println("Raspuns corect!");
                        }
                        else
                        {
                            System.out.println("Raspunsgresit!");
                        }
            intrebarecurenta++;          
            }
            else {
                //daca e ultima intrebare
                Integer rasp = 1;
                        if (rasp==Integer.parseInt(reslist.get(6*(intrebarecurenta-1)+2)))
                        {
                            raspunsuricorecte++;
                            jLabel7.setText("Raspunsuri corecte: "+raspunsuricorecte+" din "+totalrasp);
                        }
                        jLabel3.setText("");
                        jLabel4.setText("");
                        jLabel5.setText("");
                        jLabel6.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(membru.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            new user().setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(membru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(membru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(membru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(membru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new membru().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(membru.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
